ARG VERSION=v3.2.1

FROM prom/prometheus:${VERSION}

# Remove default config and replace with ours
RUN rm -f /etc/prometheus/prometheus.yml
COPY prom.yml /etc/prometheus/prometheus.yml

# Command to run Prometheus
CMD ["--config.file=/etc/prometheus/prom.yml", "--storage.tsdb.path=/prometheus", "--web.enable-remote-write-receiver", "--storage.tsdb.retention.time=30d"]
