ARG VERSION=v3.2.1

FROM prom/prometheus:${VERSION}

# Cache bust: change this value to force rebuild
ARG CACHEBUST=2

# Replace default config with ours
COPY prom.yml /etc/prometheus/prometheus.yml

CMD ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.enable-remote-write-receiver", "--storage.tsdb.retention.time=30d"]
