global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'example_api'
  #   scheme: http
  #   static_configs:
  #     - targets: ['example_api:9091']

  - job_name: 'frontend'
    scheme: https
    metrics_path: /api/metrics
    static_configs:
      - targets: ['dashboard.usehavana.com']

  - job_name: 'sftpgo'
    scheme: http
    static_configs:
      - targets: ['sftpgo-railway.railway.internal:9090']

  - job_name: 'blackbox-sftp-proxy'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets: ['upload.sftp.usehavana.com:22']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox.railway.internal:9115